### ISSUE TITLE
Missing 'FaFile_Circ'?

### ISSUE THREAD

**Issue by Jelinek-J** [ohlerlab/RiboseQC#13] opened 2020-10-20 21:20 UTC
Hi,

I tried to prepare annotation files using the current version of RiboseQC, however it ends up with the following error.

    > prepare_annotation_files('.', './Homo_sapiens.GRCh38.dna.primary_assembly.2bit', './Homo_sapiens.GRCh38.101.gtf', annotation_name='GRCh38', genome_seq='./Homo_sapiens.GRCh38.dna.primary_assembly.fa')
    fasta file passed - cancelling BSgenome creation
    Error in FaFile_Circ(genome_seq, circularRanges = circ_chroms) :
      could not find function "FaFile_Circ"

The only mention I found about the function is in [riboseqc.R](https://github.com/ohlerlab/RiboseQC/blob/master/R/riboseqc.R). It seems [FaFile_Circ.R](https://github.com/ohlerlab/RiboseQC/blob/c599e5272c1b3b005d2a76127a2f3d86d3e308cf/R/FaFile_Circ.R) disappears in June.

**Comment by zslastman** [comment] 2020-10-21 13:10
Hey Jelinek - indeed this file didn't merge into the master branch properly. The issue is now fixed.

**Closed by zslastman** 2020-10-21 13:10 UTC
